version: "3.7"

services:
  tgbotnginx:
    container_name: tgbotnginx
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
#      - ./certs:/etc/letsencrypt/live/tgbot.ru:ro
    ports:
      - mode: host
        protocol: tcp
        published: 80
        target: 80
      - mode: host
        protocol: tcp
        published: 443
        target: 443
    networks:
      - tgbot
    restart: always

  tgbotapi:
    container_name: tgbotapi
    build:
      context: ../.
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Local
      - ConnectionStrings:PostgresDb=User ID=$POSTGRES_LOGIN;
          Password=$POSTGRES_PASSWORD;Host=tgbotdb;Port=$POSTGRES_DEFAULTPORT;Database=$POSTGRES_DBNAME;Pooling=true
      - ASPNETCORE_URLS=http://+:8443
    ports:
      - mode: host
        protocol: tcp
        published: 8443
        target: 8443
    networks:
      - tgbot
    depends_on:
      - tgbotdb
    restart: always

  tgbotdb:
    container_name: tgbotdb
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_LOGIN
      - POSTGRES_USER=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DBNAME
    volumes:
      - pgdata:/var/lib/postgresql/data
      - pgconf:/etc/postgresql
      - pglog:/var/log/postgresql
    ports:
      - mode: host
        protocol: tcp
        published: $POSTGRES_DEFAULTPORT
        target: $POSTGRES_DEFAULTPORT
    networks:
      - tgbot
    restart: always

networks:
  tgbot:
    name: tgbot

volumes:
  pgdata:
    driver: local
  pgconf:
    driver: local
  pglog:
    driver: local