version: "3.7"

services:
  proxy:
    container_name: tgbotnginx
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/live/heppymonbot.ru:/etc/nginx/certs
    ports:
      - mode: host
        protocol: tcp
        published: 80
        target: 80
      - mode: host
        protocol: tcp
        published: 443
        target: 443
    networks:
      - tgbot
    restart: always

  api:
    container_name: tgbotapi
    image: heppymon/mytgbot:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Prod
      - ASPNETCORE_URLS=http://+:8443
    ports:
      - mode: host
        protocol: tcp
        published: 8443
        target: 8443
    networks:
      - tgbot
    depends_on:
      - db
    restart: always

  db:
    container_name: tgbotdb
    image: postgres:15.1-alpine3.17
    environment:
      - POSTGRES_PASSWORD=TgChatBot99
      - POSTGRES_USER=botUser
      - POSTGRES_DB=TgBot
    volumes:
      - pgdata:/var/lib/postgresql/data
      - pgconf:/etc/postgresql
      - pglog:/var/log/postgresql
    ports:
      - mode: host
        protocol: tcp
        published: 5432
        target: 5432
    networks:
      - tgbot
    restart: always

networks:
  tgbot:
    name: tgbot

volumes:
  pgdata:
    driver: local
  pgconf:
    driver: local
  pglog:
    driver: local