version: '3'

name: 'cr'

services:
  registry:
    ports:
      - 5000:5000
    restart: always
    container_name: registry
    volumes:
      - ./auth:/auth
      - ./data:/data
    environment:
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/.htpasswd
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
    image: registry:2
    networks:
      - cr

  registry-frontend:
    image: konradkleine/docker-registry-frontend:v2
    restart: always
    environment:
      ENV_DOCKER_REGISTRY_HOST: 'registry'
      ENV_DOCKER_REGISTRY_PORT: 5000
    links:
      - registry
    ports:
      - "8080:443"
    expose:
      - 443
    networks:
      - cr

networks:
  cr:
    name: cr
    driver: bridge