version: "3.7"

services:
  proxy:
    container_name: tgbotnginx
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - mode: host
        protocol: tcp
        published: 80
        target: 80
      - mode: host
        protocol: tcp
        published: 443
        target: 443
    networks:
      - tgbot
    restart: always

  api:
    container_name: tgbotapi
    image: heppymon/mytgbot:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Prod
      - ConnectionStrings:PostgresDb=User ID=$POSTGRES_LOGIN;
          Password=$POSTGRES_PASSWORD;Host=tgbotdb;Port=$POSTGRES_DEFAULTPORT;Database=$POSTGRES_DBNAME;Pooling=true
      - ASPNETCORE_URLS=http://+:8443
    ports:
      - mode: host
        protocol: tcp
        published: 8443
        target: 8443
    networks:
      - tgbot
    depends_on:
      - db
    restart: always

  tgbotdb:
    container_name: tgbotdb
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_USER=$POSTGRES_LOGIN
      - POSTGRES_DB=$POSTGRES_DBNAME
    volumes:
      - pgdata:/var/lib/postgresql/data
      - pgconf:/etc/postgresql
      - pglog:/var/log/postgresql
    ports:
      - mode: host
        protocol: tcp
        published: $POSTGRES_DEFAULTPORT
        target: $POSTGRES_DEFAULTPORT
    networks:
      - tgbot
    restart: always

  dozzle:
    container_name: dozzle
    image: amir20/dozzle:v4.6.3
    environment:
      - DOZZLE_USERNAME=dozzle
      - DOZZLE_PASSWORD=DOZZLEPASSWORDFORMYTGBOT911
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8888:8080

networks:
  tgbot:
    name: tgbot

volumes:
  pgdata:
    driver: local
  pgconf:
    driver: local
  pglog:
    driver: local