name: CheckTests

on:  
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      current:
        dotnet-version: [ '6.0.402' ]

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK ${{ current.dotnet-version }}
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: ${{ current.dotnet-version }}     
      - name: Install dependencies
        run: dotnet restore
      - name: Build project
        run: dotnet build --configuration Release --no-restore
      - name: Run tests
        run: dotnet test --no-restore --verbosity normal